# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0082217b00c2db8c2088b4618eabdd18f26fff47f10715646b5a195e7d5aa94943091886a59107a9b8fad05c4be1c2fa306cf768e46036b3122651ec20e2307d

test:
  secret_key_base: c1feba8f9a195d4fd4509b442bec0ae17f19e530e620deb5e69ca1230d6c10f87bc630f98023f539a8efb973feba24441c1e3d698c84573f59217e8397014bb6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
